#stages:
#  - trigger
#
## 触发后端 pipeline
#backend:
#  stage: trigger
#  trigger:
#    include:
#      - local: .gitlab/backend.yml
#  rules:
#    - changes:
#        - backend/**/*
#
## 触发前端 pipeline
#frontend:
#  stage: trigger
#  trigger:
#    include:
#      - local: .gitlab/frontend.yml
#  rules:
#    - changes:
#        - frontend/**/*

stages:
  - backend
  - frontend

# 后端 pipeline
backend:
  stage: backend
  script:
    - echo "触发后端构建"
  rules:
    - changes:
        - backend/**/*
  include:
    - local: .gitlab/backend.yml

# 前端 pipeline
frontend:
  stage: frontend
  script:
    - echo "触发前端构建"
  rules:
    - changes:
        - frontend/**/*
  include:
    - local: .gitlab/frontend.yml